ecomsite/ecomsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls'),name="shop")
]

ecomsite/shop/urls.py
from django.urls import path
from shop.views import index,detail,checkout
app_name="shop"
urlpatterns = [
    path('', index, name='shop_index'),
     path('<int:id>/', detail, name='productdetails'),
     path('checkout/', checkout, name='productscheckout'),
    
]

ecomsite/shop/models.py
from django.db import models

# Create your models here.


class Products(models.Model):
    title=models.CharField(max_length=200)
    price=models.FloatField()
    discount=models.FloatField()
    category=models.CharField(max_length=200)
    dec=models.TextField()
    img=models.CharField(max_length=500)

    def __str__(self) -> str:
        return self.title
    

class Order(models.Model):
    items=models.CharField(max_length=1000)
    name=models.CharField(max_length=200)
    email=models.CharField(max_length=200)
    address=models.CharField(max_length=1000)
    city=models.CharField(max_length=200)
    State=models.CharField(max_length=200)
    Zip=models.CharField(max_length=200)
    total=models.CharField(max_length=200)
    def __str__(self) -> str:
        return self.name

ecomsite/shop/views.py
from django.shortcuts import render
from shop.models import Products,Order
from django.core.paginator import Paginator
# Create your views here.


def index(request):
    product_obj=Products.objects.all()
    #serch code
    item_name =request.GET.get('item_name')
    if item_name != "" and item_name is not None:
        product_obj=product_obj.filter(title__icontains=item_name)
    
    #paginator code
    paginator=Paginator(product_obj,4)
    page=request.GET.get('page')
    product_obj=paginator.get_page(page)


    return render(request,'shop/index.html',{"product_obj":product_obj})


def detail(request,id):
    product_object=Products.objects.get(id=id)
    return render(request,'shop/detail.html',{'product_object':product_object})



def checkout(request):

    if request.method =="POST":
        items=request.POST.get('items',"")
        name=request.POST.get('name',"")
        email=request.POST.get('email',"")
        address=request.POST.get('address',"")
        city=request.POST.get('city',"")
        State=request.POST.get('State',"")
        Zip=request.POST.get('Zip',"")
        total=request.POST.get('total',"")
        order=Order(items=items,name=name,email=email,address=address,city=city,State=State,Zip=Zip,total=total)
        order.save()
    return render(request,'shop/checkout.html')

ecomsite/shop/templates/shop/checkout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
</head>

<body>
    <div class=" container">
        <div class="row">
            <div class="col-md-12 mt-3">
                <ul class="list-group" id="item_list"></ul>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" id="items" name="items">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputEmail4">Name</label>
                            <input id="name" name="name" type="text" class="form-control" id="inputEmail4"
                                placeholder="veeraveer">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputPassword4">email</label>
                            <input id="email" name="email" type="email" class="form-control" id="veera@mail.com">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputAddress">Address</label>
                        <input id="address" name="address" type="text" class="form-control" id="inputAddress"
                            placeholder="1234 Main St">
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="inputCity">City</label>
                            <input id="city" name="city" type="text" class="form-control" id="inputCity">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="inputState">State</label>
                            <input id="State" name="State" type="text" class="form-control" id="inputState">
                        </div>
                        <div class="form-group col-md-2">
                            <label for="inputZip">Zip</label>
                            <input id="Zip" name="Zip" type="text" class="form-control" id="inputZip">
                        </div>
                        <div class="form-group col-md-2">
                            <label for="inputZip">amount to be paid</label>
                            <input readonly="" type="text" class="form-control" id="total" name="total">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">place order</button>
                </form>
            </div>

        </div>



    </div>
</body>
<script type="text/javascript">
    if (localStorage.getItem('cart') == null) {
        var cart = {};

    }
    else {
        cart = JSON.parse(localStorage.getItem('cart'));
    }
    let total = 0;
    for (item in cart) {



        let name = cart[item][1]
        let quantity = cart[item][0]
        let price = cart[item][2]
        total = total + cart[item][2]


        itemstring = `<li class="list-group-item">${name}<span class ="">${quantity}<span class ="badge-warning badge-pill">${price}</li>`

        $('#item_list').append(itemstring)
    }
    tottaprice = `<li class="list-group-item d-flex justify-contnet-between align-items-center"><b>your total price</b>${total}</li>`
    $('#item_list').append(tottaprice)
    $('#items').val(JSON.stringify(cart));
    $('#total').val(total);


</script>

</html>

ecomsite/shop/templates/shop/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>

<body>

    <div class="container mt-4">
        <div class="row">

            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <img src="{{ product_object.img }}" class="img-fluid" alt="Product Image">
                    </div>
                </div>
            </div>

            <div class="col-md-6">

                <div class="row mb-2">
                    <div class="col-md-12">
                        <h3>{{ product_object.title }}</h3>
                    </div>
                </div>

                <div class="row mb-2">
                    <div class="col-md-12">
                        <p><strong>Price:</strong> {{ product_object.price }}</p>
                    </div>
                </div>

                <div class="row mb-2">
                    <div class="col-md-12">
                        <p><strong>Discount:</strong> {{ product_object.discount }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <p><strong>Description:</strong> {{ product_object.dec }}</p>
                    </div>
                </div>

            </div>

        </div>
    </div>

    <!-- Bootstrap JS (optional, use it only if needed) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>

</body>

</html>

ecomsite/shop/templates/shop/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>



    <link rel="stylesheet" href="{% static 'shop/indexstyle.css' %}">
    <title>Document</title>
</head>

<body>


    <div class="container">


        <div class=" row">
            <div class=" col-md-12">

                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="{% url  'shop:shop_index'   %}">meworkstelugu</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url  'shop:shop_index'   %}">Home <span
                                        class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Features</a>
                            </li>
                            <li class="nav-item">
                                <button id="cart" type="button" class="btn btn-secondary" data-container="body"
                                    data-html="true" data-toggle="popover" data-placement="bottom"
                                    data-content="Bottom popover">
                                    cart(0)
                                </button>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link disabled">Disabled</a>
                            </li>
                        </ul>
                    </div>
                </nav>

            </div>
        </div>

        <div class="row">
            <div class=" col-md-12 mt-4">
                <form class="card card-sm">
                    <div class="card-body row no-gutters aligen-items-center">
                        <div class="col">
                            <input type="search" name="item_name" placeholder="serch products"
                                class="form-control form-control-borderless">
                        </div>
                        <div class="col=auto">
                            <button class="btn btn-success" type="submit">serch</button>

                        </div>
                    </div>

                </form>
            </div>
        </div>



        <div class="row">
            {% for product in product_obj %}
            <div class=" col-md-3  mt-4">
                <div class="card">
                    <img src="{{product.img}}" class="card-img-top " style="height:300; width:300">
                    <div class="card-body">
                        <div id="nm{{product.id}}" class="card-title product-title">{{product.title}}</div>
                        <div id="price{{product.id}}" class="card-text price-tag">{{product.price}}</div>
                        <a href="{% url  'shop:productdetails'  product.id  %}" class="btn btn-warning">view</a>
                        <a id="{{product.id}}" class="btn btn-warning atc">add to cat</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>




        <div class="row">
            <div class=" col-md-3 offset-md-4 m-2">
                <ul class="pagination">
                    {% if product_obj.has_previous %}

                    <li class="page-item">
                        <a class="page-link" href="?page={{  product_obj.previous_page_number  }}">previous</a>
                    </li>
                    {% endif %}



                    <li class="page-item active">
                        <a class="page-link" href="?page={{  product_obj.number  }}">current {{product_obj.number }}</a>
                    </li>





                    {% if product_obj.has_next %}

                    <li class="page-item">
                        <a class="page-link" href="?page={{  product_obj.next_page_number  }}">next</a>
                    </li>

                    {% endif %}
                </ul>

            </div>
        </div>


    </div>























</body>
<script type="text/javascript">

    console.log('this is working');

    if (localStorage.getItem('cart') == null) {
        var cart = {};

    }
    else {
        cart = JSON.parse(localStorage.getItem('cart'));
    }


    $(document).on('click', '.atc', function () {
        console.log("cart btn click")
        var item_id = this.id.toString();
        console.log(item_id)

        if (cart[item_id] != undefined) {
            quantity = cart[item_id][0] + 1
            cart[item_id][0] = quantity
            cart[item_id][2] = cart[item_id][2] + parseFloat(document.getElementById("price" + item_id).innerHTML);

        }
        else {
            quantity = 1
            price = parseFloat(document.getElementById("price" + item_id).innerHTML);
            name = document.getElementById('nm' + item_id).innerHTML;
            cart[item_id] = [quantity, name, price];


        }
        console.log(cart)
        localStorage.setItem('cart', JSON.stringify(cart))
        document.getElementById('cart').innerHTML = "cart(" + Object.keys(cart).length + ")"
        //console.log(Object.keys(cart).length);

    });
    s = DisplayCart(cart)
    $(function () {
        $('[data-toggle="popover"]').popover();
        document.getElementById('cart').setAttribute('data-content', s)

    });
    DisplayCart(cart);
    function DisplayCart(cart) {
        var cartString = "";
        cartString += "<h5>This is your cart</h5>";
        var cartIndex = 1;

        let cartobj = JSON.parse(localStorage.getItem('cart'))
        for (var x in cartobj) {
            var element = document.getElementById("nm" + x);
            let cartobj = JSON.parse(localStorage.getItem('cart'))


            if (cartobj) {
                cartString += cartIndex;
                //cartString += element.innerHTML + "Qty:" + cart[x][0] + "</br>";
                cartString += cartobj[x][1] + "Qty:" + cartobj[x][0] + "</br>";
                cartIndex += 1;

            } else {
                console.error("Element with ID 'nm" + x + "' not found.");
            }
        }
        cartString += "<a href='/shop/checkout'><button class='btn btn-warning' id='checkout'>Checkout</button></a>";
        return cartString

    }

</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

</html>